base_configs:
- ../base/dataset/climate-model-simulation-crashes.yml
- ../base/runner/climate-model-simulation-crashes.yml
- ./CoT_llm_tree.yml
- tree/CoT.yml
- ./common.yml
config:
  exp_name: CoT-climate-model-simulation-crashes-baseline
  template: template/basic.jinja
  tree_only: false
