base_configs:
  - ../base/dataset/car.yml
  - ../base/runner/chatgpt.yml
  - ./CoT_llm_tree.yml
  - tree/CoT.yml
  - ./common.yml

config:
  exp_name: CoT_tree-car-baseline
  template: template/basic.jinja
  tree_only: False