base_configs:
- ../base/dataset/blood.yml
- ../base/runner/chatgpt.yml
- ./CoT_llm_tree.yml
- tree/CoT.yml
- ./common.yml
config:
  exp_name: CoT-blood-baseline
  template: template/basic.jinja
  tree_only: false
