base_configs:
- ../base/dataset/electricity.yml
- ../base/runner/chatgpt.yml
- ./direct_llm_tree.yml
- tree/llm_gen_directly.yml
- ./common.yml
config:
  exp_name: llm_gen_tree-electricity-baseline
  template: template/basic.jinja
  tree_only: false
