base_configs:
- ../base/dataset/abalone.yml
- ../base/runner/chatgpt.yml
- ./ToT_llm_tree.yml
- tree/ToT.yml
- ./common.yml
config:
  exp_name: ToT-abalone-baseline
  template: template/basic.jinja
  tree_only: false
