base_configs:
  - ../base/dataset/diabetes.yml
  - ../base/runner/chatgpt.yml
  - ./ToT_llm_tree.yml
  - tree/ToT.yml
  - ./common.yml

config:
  exp_name: ToT_tree-diabetes-baseline
  template: template/basic.jinja
  tree_only: False