base_configs:
- ../base/dataset/breast-cancer-coimbra.yml
- ../base/runner/chatgpt.yml
- ./ToT_llm_tree.yml
- tree/ToT.yml
- ./common.yml
config:
  exp_name: ToT-breast-cancer-coimbra-baseline
  template: template/basic.jinja
  tree_only: false
