base_configs:
- ../base/dataset/breast-cancer-coimbra.yml
- ../base/runner/chatgpt.yml
- ../base/common.yml
- ./strategy/feature_bagging.yml
- ./common.yml
config:
  exp_name: chatgpt-breast-cancer-coimbra
