config:
  tree_type: CoT
  tree_args:
    max_depth: 3
    llm_tree_args:
    model_name: "togethercomputer/llama-2-70b-chat"
  random_seed: 42
  num_tests_per_set: 5
  test_size: 100
  test_batch: 8
  use_tree_rules: True
  