config:
  tree_type: ToT
  tree_args:
    max_depth: 3
    llm_tree_args:
    model_name: qwen/qwen3-235b-a22b-thinking-2507
  random_seed: 0
  num_tests_per_set: 5
  test_size: 100
  test_batch: 5
  use_tree_rules: True
  