config:
  runner: openai_api
  runner_args:
    model_name: meta-llama/Meta-Llama-3-8B-Instruct-Turbo
    api_base: https://api.together.xyz/v1
    openai_api_key: 'tgp_v1_mZ8owe_e9GB3gtfS3oIhr-f7LNbb1Sc1SLkISv_yEfc'
    request_interval: 0.2
    timeout: 20
